[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 200

[theme]
primaryColor = "#BD3039"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F6F7"
textColor = "#0C2340"
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
baseFontSize = 16
baseFontWeight = 400

[theme.sidebar]
backgroundColor = "#F5F6F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0C2340"
font = "sans-serif"
headingFont = "sans-serif"
